### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by wang820824** [zhongwangninja/MyActions#4]
https://github.com/sazs34/MyActions/raw/master/.github/workflows/repo-sync.yml 打不开了，请指导一下，你有原文件么

**Comment by zhongwangninja** [comment]
这个链接我是能正常打开的

``` yml
# File: .github/workflows/repo-sync.yml
name: sync-sazs34-scripts
on:
  schedule:
    - cron: '5 0,7,15 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-sazs34-scripts
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT || github.event.client_payload.PAT }} #此处PAT需要申请，教程详见：https://www.jianshu.com/p/bb82b3ad1d11
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync sazs34-scripts
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/sazs34/MyActions.git"
          source_branch: "master"
          destination_branch: "main"
          github_token: ${{ secrets.PAT || github.event.client_payload.PAT }}
```
